/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo_synch.v:1.1-59.10" *)
module synch_fifo_bram(clk, rst_n, wr_en, rd_en, data_in, full, empty, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[0] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[1] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[2] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[3] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[4] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[5] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[6] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[7] ;
  (* src = "fifo_synch.v:5.36-5.39" *)
  input clk;
  wire clk;
  (* src = "fifo_synch.v:9.36-9.43" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "fifo_synch.v:12.36-12.44" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "fifo_synch.v:11.36-11.41" *)
  output empty;
  wire empty;
  (* src = "fifo_synch.v:10.36-10.40" *)
  output full;
  wire full;
  (* src = "fifo_synch.v:8.36-8.41" *)
  input rd_en;
  wire rd_en;
  (* src = "fifo_synch.v:23.24-23.30" *)
  wire [3:0] rd_ptr;
  (* src = "fifo_synch.v:24.26-24.36" *)
  wire [2:0] rd_ptr_reg;
  (* src = "fifo_synch.v:6.36-6.41" *)
  input rst_n;
  wire rst_n;
  (* src = "fifo_synch.v:7.36-7.41" *)
  input wr_en;
  wire wr_en;
  (* src = "fifo_synch.v:22.24-22.30" *)
  wire [3:0] wr_ptr;
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(rd_ptr[2]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(rd_ptr_reg[1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(rst_n),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _154_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xor2_1 _155_ (
    .A(rd_ptr[1]),
    .B(wr_ptr[1]),
    .X(_079_)
  );
  sky130_fd_sc_hd__xor2_1 _156_ (
    .A(rd_ptr[0]),
    .B(wr_ptr[0]),
    .X(_080_)
  );
  sky130_fd_sc_hd__xor2_1 _157_ (
    .A(rd_ptr[2]),
    .B(wr_ptr[2]),
    .X(_081_)
  );
  sky130_fd_sc_hd__or3_1 _158_ (
    .A(_079_),
    .B(_080_),
    .C(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _159_ (
    .A(rd_ptr[3]),
    .B(wr_ptr[3]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xor2_1 _160_ (
    .A(rd_ptr[3]),
    .B(wr_ptr[3]),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(_082_),
    .B(_083_),
    .Y(full)
  );
  sky130_fd_sc_hd__o41a_1 _162_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_081_),
    .A4(_083_),
    .B1(wr_en),
    .X(_085_)
  );
  sky130_fd_sc_hd__o41ai_1 _163_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_081_),
    .A4(_083_),
    .B1(wr_en),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand4_1 _164_ (
    .A(wr_ptr[2]),
    .B(rst_n),
    .C(_078_),
    .D(_085_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _165_ (
    .A0(data_in[1]),
    .A1(\bram[4] [1]),
    .S(_087_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(data_in[2]),
    .A1(\bram[4] [2]),
    .S(_087_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(data_in[3]),
    .A1(\bram[4] [3]),
    .S(_087_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(data_in[4]),
    .A1(\bram[4] [4]),
    .S(_087_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _169_ (
    .A0(data_in[5]),
    .A1(\bram[4] [5]),
    .S(_087_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _170_ (
    .A0(data_in[6]),
    .A1(\bram[4] [6]),
    .S(_087_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _171_ (
    .A0(data_in[7]),
    .A1(\bram[4] [7]),
    .S(_087_),
    .X(_006_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _172_ (
    .A(wr_ptr[0]),
    .SLEEP(wr_ptr[1]),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand4_1 _173_ (
    .A(wr_ptr[2]),
    .B(rst_n),
    .C(_085_),
    .D(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _174_ (
    .A0(data_in[0]),
    .A1(\bram[5] [0]),
    .S(_089_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _175_ (
    .A0(data_in[1]),
    .A1(\bram[5] [1]),
    .S(_089_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(data_in[2]),
    .A1(\bram[5] [2]),
    .S(_089_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _177_ (
    .A0(data_in[3]),
    .A1(\bram[5] [3]),
    .S(_089_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _178_ (
    .A0(data_in[4]),
    .A1(\bram[5] [4]),
    .S(_089_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _179_ (
    .A0(data_in[5]),
    .A1(\bram[5] [5]),
    .S(_089_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _180_ (
    .A0(data_in[6]),
    .A1(\bram[5] [6]),
    .S(_089_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _181_ (
    .A0(data_in[7]),
    .A1(\bram[5] [7]),
    .S(_089_),
    .X(_014_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _182_ (
    .A(wr_ptr[1]),
    .SLEEP(wr_ptr[0]),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(wr_ptr[2]),
    .B(rst_n),
    .C(_085_),
    .D(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _184_ (
    .A0(data_in[0]),
    .A1(\bram[6] [0]),
    .S(_091_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _185_ (
    .A0(data_in[1]),
    .A1(\bram[6] [1]),
    .S(_091_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _186_ (
    .A0(data_in[2]),
    .A1(\bram[6] [2]),
    .S(_091_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _187_ (
    .A0(data_in[3]),
    .A1(\bram[6] [3]),
    .S(_091_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(data_in[4]),
    .A1(\bram[6] [4]),
    .S(_091_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _189_ (
    .A0(data_in[5]),
    .A1(\bram[6] [5]),
    .S(_091_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _190_ (
    .A0(data_in[6]),
    .A1(\bram[6] [6]),
    .S(_091_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _191_ (
    .A0(data_in[7]),
    .A1(\bram[6] [7]),
    .S(_091_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _192_ (
    .A(_082_),
    .B(_084_),
    .Y(empty)
  );
  sky130_fd_sc_hd__o41ai_1 _193_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_081_),
    .A4(_084_),
    .B1(rd_en),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o211ai_1 _194_ (
    .A1(_082_),
    .A2(_084_),
    .B1(rd_ptr[0]),
    .C1(rd_en),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _195_ (
    .A(rd_ptr[0]),
    .B(_092_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _196_ (
    .A(rd_ptr[1]),
    .B(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a22o_1 _197_ (
    .A1(rd_ptr[1]),
    .A2(_093_),
    .B1(_094_),
    .B2(rd_ptr[0]),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[1]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(_092_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _200_ (
    .A(_075_),
    .B(_096_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _201_ (
    .A(_075_),
    .B(_092_),
    .C(_095_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xor2_1 _202_ (
    .A(rd_ptr[3]),
    .B(_097_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__and3_1 _204_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .C(wr_ptr[2]),
    .X(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _205_ (
    .A(rst_n),
    .B(_085_),
    .C(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(data_in[0]),
    .A1(\bram[7] [0]),
    .S(_100_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(data_in[1]),
    .A1(\bram[7] [1]),
    .S(_100_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _208_ (
    .A0(data_in[2]),
    .A1(\bram[7] [2]),
    .S(_100_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _209_ (
    .A0(data_in[3]),
    .A1(\bram[7] [3]),
    .S(_100_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(data_in[4]),
    .A1(\bram[7] [4]),
    .S(_100_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _211_ (
    .A0(data_in[5]),
    .A1(\bram[7] [5]),
    .S(_100_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _212_ (
    .A0(data_in[6]),
    .A1(\bram[7] [6]),
    .S(_100_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(data_in[7]),
    .A1(\bram[7] [7]),
    .S(_100_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(rd_ptr_reg[0]),
    .B(_092_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_093_),
    .B(_101_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _216_ (
    .A1(_076_),
    .A2(_092_),
    .B1(_094_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(rd_ptr_reg[2]),
    .B(_092_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _218_ (
    .A1(_075_),
    .A2(_092_),
    .B1(_102_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(wr_ptr[0]),
    .B(_085_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _220_ (
    .A(wr_ptr[0]),
    .B(_086_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a22o_1 _221_ (
    .A1(_085_),
    .A2(_088_),
    .B1(_103_),
    .B2(wr_ptr[1]),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_086_),
    .B(_098_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xor2_1 _223_ (
    .A(wr_ptr[2]),
    .B(_104_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_085_),
    .B(_099_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _225_ (
    .A(wr_ptr[3]),
    .B(_105_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand4b_1 _226_ (
    .A_N(wr_ptr[2]),
    .B(rst_n),
    .C(_078_),
    .D(_085_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _227_ (
    .A0(data_in[0]),
    .A1(\bram[0] [0]),
    .S(_106_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _228_ (
    .A0(data_in[1]),
    .A1(\bram[0] [1]),
    .S(_106_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _229_ (
    .A0(data_in[2]),
    .A1(\bram[0] [2]),
    .S(_106_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _230_ (
    .A0(data_in[3]),
    .A1(\bram[0] [3]),
    .S(_106_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _231_ (
    .A0(data_in[4]),
    .A1(\bram[0] [4]),
    .S(_106_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _232_ (
    .A0(data_in[5]),
    .A1(\bram[0] [5]),
    .S(_106_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _233_ (
    .A0(data_in[6]),
    .A1(\bram[0] [6]),
    .S(_106_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _234_ (
    .A0(data_in[7]),
    .A1(\bram[0] [7]),
    .S(_106_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor4b_1 _235_ (
    .A(wr_ptr[2]),
    .B(_077_),
    .C(_086_),
    .D_N(_088_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _236_ (
    .A0(\bram[1] [0]),
    .A1(data_in[0]),
    .S(_107_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _237_ (
    .A0(\bram[1] [1]),
    .A1(data_in[1]),
    .S(_107_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(\bram[1] [2]),
    .A1(data_in[2]),
    .S(_107_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _239_ (
    .A0(\bram[1] [3]),
    .A1(data_in[3]),
    .S(_107_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _240_ (
    .A0(\bram[1] [4]),
    .A1(data_in[4]),
    .S(_107_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(\bram[1] [5]),
    .A1(data_in[5]),
    .S(_107_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(\bram[1] [6]),
    .A1(data_in[6]),
    .S(_107_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(\bram[1] [7]),
    .A1(data_in[7]),
    .S(_107_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor4b_1 _244_ (
    .A(wr_ptr[2]),
    .B(_077_),
    .C(_086_),
    .D_N(_090_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(\bram[2] [0]),
    .A1(data_in[0]),
    .S(_108_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(\bram[2] [1]),
    .A1(data_in[1]),
    .S(_108_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(\bram[2] [2]),
    .A1(data_in[2]),
    .S(_108_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(\bram[2] [3]),
    .A1(data_in[3]),
    .S(_108_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(\bram[2] [4]),
    .A1(data_in[4]),
    .S(_108_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(\bram[2] [5]),
    .A1(data_in[5]),
    .S(_108_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(\bram[2] [6]),
    .A1(data_in[6]),
    .S(_108_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(\bram[2] [7]),
    .A1(data_in[7]),
    .S(_108_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nor4_1 _253_ (
    .A(wr_ptr[2]),
    .B(_077_),
    .C(_086_),
    .D(_098_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _254_ (
    .A0(\bram[3] [0]),
    .A1(data_in[0]),
    .S(_109_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _255_ (
    .A0(\bram[3] [1]),
    .A1(data_in[1]),
    .S(_109_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _256_ (
    .A0(\bram[3] [2]),
    .A1(data_in[2]),
    .S(_109_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _257_ (
    .A0(\bram[3] [3]),
    .A1(data_in[3]),
    .S(_109_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _258_ (
    .A0(\bram[3] [4]),
    .A1(data_in[4]),
    .S(_109_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _259_ (
    .A0(\bram[3] [5]),
    .A1(data_in[5]),
    .S(_109_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _260_ (
    .A0(\bram[3] [6]),
    .A1(data_in[6]),
    .S(_109_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _261_ (
    .A0(\bram[3] [7]),
    .A1(data_in[7]),
    .S(_109_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _262_ (
    .A0(data_in[0]),
    .A1(\bram[4] [0]),
    .S(_087_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(rd_ptr_reg[0]),
    .B(rd_ptr_reg[1]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(rd_ptr_reg[2]),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _265_ (
    .A(rd_ptr_reg[0]),
    .B(_076_),
    .C(rd_ptr_reg[2]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a22oi_1 _266_ (
    .A1(\bram[3] [0]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [0]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor3b_1 _267_ (
    .A(rd_ptr_reg[1]),
    .B(rd_ptr_reg[2]),
    .C_N(rd_ptr_reg[0]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__and3_1 _268_ (
    .A(rd_ptr_reg[0]),
    .B(_076_),
    .C(rd_ptr_reg[2]),
    .X(_115_)
  );
  sky130_fd_sc_hd__a22oi_1 _269_ (
    .A1(\bram[1] [0]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [0]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__and3_1 _270_ (
    .A(rd_ptr_reg[0]),
    .B(rd_ptr_reg[1]),
    .C(rd_ptr_reg[2]),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor3_1 _271_ (
    .A(rd_ptr_reg[0]),
    .B(rd_ptr_reg[1]),
    .C(rd_ptr_reg[2]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a22oi_1 _272_ (
    .A1(\bram[7] [0]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [0]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor3b_1 _273_ (
    .A(rd_ptr_reg[0]),
    .B(_076_),
    .C_N(rd_ptr_reg[2]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor3b_1 _274_ (
    .A(rd_ptr_reg[0]),
    .B(rd_ptr_reg[1]),
    .C_N(rd_ptr_reg[2]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22oi_1 _275_ (
    .A1(\bram[6] [0]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [0]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand4_1 _276_ (
    .A(_113_),
    .B(_116_),
    .C(_119_),
    .D(_122_),
    .Y(data_out[0])
  );
  sky130_fd_sc_hd__a22oi_1 _277_ (
    .A1(\bram[3] [1]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [1]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a22oi_1 _278_ (
    .A1(\bram[1] [1]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [1]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a22oi_1 _279_ (
    .A1(\bram[7] [1]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [1]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a22oi_1 _280_ (
    .A1(\bram[6] [1]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [1]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand4_1 _281_ (
    .A(_123_),
    .B(_124_),
    .C(_125_),
    .D(_126_),
    .Y(data_out[1])
  );
  sky130_fd_sc_hd__a22oi_1 _282_ (
    .A1(\bram[3] [2]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [2]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a22oi_1 _283_ (
    .A1(\bram[1] [2]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [2]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a22oi_1 _284_ (
    .A1(\bram[7] [2]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [2]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22oi_1 _285_ (
    .A1(\bram[6] [2]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [2]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand4_1 _286_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .D(_130_),
    .Y(data_out[2])
  );
  sky130_fd_sc_hd__a22oi_1 _287_ (
    .A1(\bram[3] [3]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [3]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a22oi_1 _288_ (
    .A1(\bram[1] [3]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [3]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a22oi_1 _289_ (
    .A1(\bram[7] [3]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [3]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a22oi_1 _290_ (
    .A1(\bram[6] [3]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [3]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand4_1 _291_ (
    .A(_131_),
    .B(_132_),
    .C(_133_),
    .D(_134_),
    .Y(data_out[3])
  );
  sky130_fd_sc_hd__a22oi_1 _292_ (
    .A1(\bram[3] [4]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [4]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a22oi_1 _293_ (
    .A1(\bram[1] [4]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [4]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a22oi_1 _294_ (
    .A1(\bram[7] [4]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [4]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a22oi_1 _295_ (
    .A1(\bram[6] [4]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [4]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand4_1 _296_ (
    .A(_135_),
    .B(_136_),
    .C(_137_),
    .D(_138_),
    .Y(data_out[4])
  );
  sky130_fd_sc_hd__a22oi_1 _297_ (
    .A1(\bram[3] [5]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [5]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a22oi_1 _298_ (
    .A1(\bram[1] [5]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [5]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a22oi_1 _299_ (
    .A1(\bram[7] [5]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [5]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a22oi_1 _300_ (
    .A1(\bram[6] [5]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [5]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand4_1 _301_ (
    .A(_139_),
    .B(_140_),
    .C(_141_),
    .D(_142_),
    .Y(data_out[5])
  );
  sky130_fd_sc_hd__a22oi_1 _302_ (
    .A1(\bram[3] [6]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [6]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a22oi_1 _303_ (
    .A1(\bram[1] [6]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [6]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a22oi_1 _304_ (
    .A1(\bram[7] [6]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [6]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a22oi_1 _305_ (
    .A1(\bram[6] [6]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [6]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand4_1 _306_ (
    .A(_143_),
    .B(_144_),
    .C(_145_),
    .D(_146_),
    .Y(data_out[6])
  );
  sky130_fd_sc_hd__a22oi_1 _307_ (
    .A1(\bram[3] [7]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [7]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a22oi_1 _308_ (
    .A1(\bram[1] [7]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [7]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a22oi_1 _309_ (
    .A1(\bram[7] [7]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [7]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a22oi_1 _310_ (
    .A1(\bram[6] [7]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [7]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand4_1 _311_ (
    .A(_147_),
    .B(_148_),
    .C(_149_),
    .D(_150_),
    .Y(data_out[7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _312_ (
    .CLK(clk),
    .D(_027_),
    .Q(\bram[7] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _313_ (
    .CLK(clk),
    .D(_028_),
    .Q(\bram[7] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _314_ (
    .CLK(clk),
    .D(_029_),
    .Q(\bram[7] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _315_ (
    .CLK(clk),
    .D(_030_),
    .Q(\bram[7] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _316_ (
    .CLK(clk),
    .D(_031_),
    .Q(\bram[7] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _317_ (
    .CLK(clk),
    .D(_032_),
    .Q(\bram[7] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _318_ (
    .CLK(clk),
    .D(_033_),
    .Q(\bram[7] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _319_ (
    .CLK(clk),
    .D(_034_),
    .Q(\bram[7] [7])
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _320_ (
    .CLK(clk),
    .D(_035_),
    .Q(rd_ptr_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _321_ (
    .CLK(clk),
    .D(_036_),
    .Q(rd_ptr_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _322_ (
    .CLK(clk),
    .D(_037_),
    .Q(rd_ptr_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfrtp_1 _323_ (
    .CLK(clk),
    .D(_038_),
    .Q(wr_ptr[0]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfrtp_1 _324_ (
    .CLK(clk),
    .D(_039_),
    .Q(wr_ptr[1]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfrtp_1 _325_ (
    .CLK(clk),
    .D(_040_),
    .Q(wr_ptr[2]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfrtp_1 _326_ (
    .CLK(clk),
    .D(_041_),
    .Q(wr_ptr[3]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _327_ (
    .CLK(clk),
    .D(_042_),
    .Q(\bram[0] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _328_ (
    .CLK(clk),
    .D(_043_),
    .Q(\bram[0] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _329_ (
    .CLK(clk),
    .D(_044_),
    .Q(\bram[0] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _330_ (
    .CLK(clk),
    .D(_045_),
    .Q(\bram[0] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _331_ (
    .CLK(clk),
    .D(_046_),
    .Q(\bram[0] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _332_ (
    .CLK(clk),
    .D(_047_),
    .Q(\bram[0] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _333_ (
    .CLK(clk),
    .D(_048_),
    .Q(\bram[0] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _334_ (
    .CLK(clk),
    .D(_049_),
    .Q(\bram[0] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _335_ (
    .CLK(clk),
    .D(_050_),
    .Q(\bram[1] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _336_ (
    .CLK(clk),
    .D(_051_),
    .Q(\bram[1] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _337_ (
    .CLK(clk),
    .D(_052_),
    .Q(\bram[1] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _338_ (
    .CLK(clk),
    .D(_053_),
    .Q(\bram[1] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _339_ (
    .CLK(clk),
    .D(_054_),
    .Q(\bram[1] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _340_ (
    .CLK(clk),
    .D(_055_),
    .Q(\bram[1] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _341_ (
    .CLK(clk),
    .D(_056_),
    .Q(\bram[1] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _342_ (
    .CLK(clk),
    .D(_057_),
    .Q(\bram[1] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _343_ (
    .CLK(clk),
    .D(_058_),
    .Q(\bram[2] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _344_ (
    .CLK(clk),
    .D(_059_),
    .Q(\bram[2] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _345_ (
    .CLK(clk),
    .D(_060_),
    .Q(\bram[2] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _346_ (
    .CLK(clk),
    .D(_061_),
    .Q(\bram[2] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _347_ (
    .CLK(clk),
    .D(_062_),
    .Q(\bram[2] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _348_ (
    .CLK(clk),
    .D(_063_),
    .Q(\bram[2] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _349_ (
    .CLK(clk),
    .D(_064_),
    .Q(\bram[2] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _350_ (
    .CLK(clk),
    .D(_065_),
    .Q(\bram[2] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _351_ (
    .CLK(clk),
    .D(_066_),
    .Q(\bram[3] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _352_ (
    .CLK(clk),
    .D(_067_),
    .Q(\bram[3] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _353_ (
    .CLK(clk),
    .D(_068_),
    .Q(\bram[3] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _354_ (
    .CLK(clk),
    .D(_069_),
    .Q(\bram[3] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _355_ (
    .CLK(clk),
    .D(_070_),
    .Q(\bram[3] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _356_ (
    .CLK(clk),
    .D(_071_),
    .Q(\bram[3] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(_072_),
    .Q(\bram[3] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(_073_),
    .Q(\bram[3] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(_074_),
    .Q(\bram[4] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(_000_),
    .Q(\bram[4] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(_001_),
    .Q(\bram[4] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _362_ (
    .CLK(clk),
    .D(_002_),
    .Q(\bram[4] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _363_ (
    .CLK(clk),
    .D(_003_),
    .Q(\bram[4] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _364_ (
    .CLK(clk),
    .D(_004_),
    .Q(\bram[4] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(_005_),
    .Q(\bram[4] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(_006_),
    .Q(\bram[4] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(_007_),
    .Q(\bram[5] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(_008_),
    .Q(\bram[5] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(_009_),
    .Q(\bram[5] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(_010_),
    .Q(\bram[5] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_011_),
    .Q(\bram[5] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_012_),
    .Q(\bram[5] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _373_ (
    .CLK(clk),
    .D(_013_),
    .Q(\bram[5] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_014_),
    .Q(\bram[5] [7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_015_),
    .Q(\bram[6] [0])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_016_),
    .Q(\bram[6] [1])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_017_),
    .Q(\bram[6] [2])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_018_),
    .Q(\bram[6] [3])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_019_),
    .Q(\bram[6] [4])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_020_),
    .Q(\bram[6] [5])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_021_),
    .Q(\bram[6] [6])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_022_),
    .Q(\bram[6] [7])
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk),
    .D(_023_),
    .Q(rd_ptr[0]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_024_),
    .Q(rd_ptr[1]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_025_),
    .Q(rd_ptr[2]),
    .RESET_B(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_026_),
    .Q(rd_ptr[3]),
    .RESET_B(rst_n)
  );
endmodule
