/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "synch_fifo.v:1.1-45.10" *)
module synch_fifo(clk, rst, wr_en, rd_en, data_in, full, empty, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  (* force_downto = 32'd1 *)
  (* src = "synch_fifo.v:29.23-29.36|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _232_;
  (* force_downto = 32'd1 *)
  (* src = "synch_fifo.v:35.23-35.36|synch_fifo.v:29.23-29.36|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _233_;
  (* src = "synch_fifo.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "synch_fifo.v:6.17-6.24" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "synch_fifo.v:9.22-9.30" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "synch_fifo.v:8.12-8.17" *)
  output empty;
  wire empty;
  (* src = "synch_fifo.v:7.12-7.16" *)
  output full;
  wire full;
  (* src = "synch_fifo.v:14.9-14.10" *)
  wire [31:0] i;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[0] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[1] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[2] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[3] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[4] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[5] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[6] ;
  (* src = "synch_fifo.v:12.11-12.17" *)
  wire [7:0] \memory[7] ;
  (* src = "synch_fifo.v:5.11-5.16" *)
  input rd_en;
  wire rd_en;
  (* src = "synch_fifo.v:13.19-13.25" *)
  wire [3:0] rd_ptr;
  (* src = "synch_fifo.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "synch_fifo.v:4.11-4.16" *)
  input wr_en;
  wire wr_en;
  (* src = "synch_fifo.v:13.11-13.17" *)
  wire [3:0] wr_ptr;
  INV_X1 _234_ (
    .A(wr_en),
    .ZN(_084_)
  );
  NOR2_X1 _235_ (
    .A1(wr_ptr[0]),
    .A2(_003_),
    .ZN(_085_)
  );
  NOR2_X1 _236_ (
    .A1(_084_),
    .A2(_002_),
    .ZN(_086_)
  );
  NAND2_X1 _237_ (
    .A1(_085_),
    .A2(_086_),
    .ZN(_087_)
  );
  MUX2_X1 _238_ (
    .A(data_in[1]),
    .B(\memory[6] [1]),
    .S(_087_),
    .Z(_004_)
  );
  MUX2_X1 _239_ (
    .A(data_in[2]),
    .B(\memory[6] [2]),
    .S(_087_),
    .Z(_005_)
  );
  MUX2_X1 _240_ (
    .A(data_in[3]),
    .B(\memory[6] [3]),
    .S(_087_),
    .Z(_006_)
  );
  MUX2_X1 _241_ (
    .A(data_in[4]),
    .B(\memory[6] [4]),
    .S(_087_),
    .Z(_007_)
  );
  MUX2_X1 _242_ (
    .A(data_in[5]),
    .B(\memory[6] [5]),
    .S(_087_),
    .Z(_008_)
  );
  MUX2_X1 _243_ (
    .A(data_in[6]),
    .B(\memory[6] [6]),
    .S(_087_),
    .Z(_009_)
  );
  MUX2_X1 _244_ (
    .A(data_in[7]),
    .B(\memory[6] [7]),
    .S(_087_),
    .Z(_010_)
  );
  NOR2_X1 _245_ (
    .A1(_232_[0]),
    .A2(_003_),
    .ZN(_088_)
  );
  NAND2_X1 _246_ (
    .A1(_086_),
    .A2(_088_),
    .ZN(_089_)
  );
  MUX2_X1 _247_ (
    .A(data_in[0]),
    .B(\memory[7] [0]),
    .S(_089_),
    .Z(_011_)
  );
  MUX2_X1 _248_ (
    .A(data_in[1]),
    .B(\memory[7] [1]),
    .S(_089_),
    .Z(_012_)
  );
  MUX2_X1 _249_ (
    .A(data_in[2]),
    .B(\memory[7] [2]),
    .S(_089_),
    .Z(_013_)
  );
  MUX2_X1 _250_ (
    .A(data_in[3]),
    .B(\memory[7] [3]),
    .S(_089_),
    .Z(_014_)
  );
  MUX2_X1 _251_ (
    .A(data_in[4]),
    .B(\memory[7] [4]),
    .S(_089_),
    .Z(_015_)
  );
  MUX2_X1 _252_ (
    .A(data_in[5]),
    .B(\memory[7] [5]),
    .S(_089_),
    .Z(_016_)
  );
  MUX2_X1 _253_ (
    .A(data_in[6]),
    .B(\memory[7] [6]),
    .S(_089_),
    .Z(_017_)
  );
  MUX2_X1 _254_ (
    .A(data_in[7]),
    .B(\memory[7] [7]),
    .S(_089_),
    .Z(_018_)
  );
  NOR3_X1 _255_ (
    .A1(_233_[0]),
    .A2(_000_),
    .A3(_001_),
    .ZN(_090_)
  );
  NOR3_X1 _256_ (
    .A1(rd_ptr[0]),
    .A2(rd_ptr[1]),
    .A3(rd_ptr[2]),
    .ZN(_091_)
  );
  AOI22_X1 _257_ (
    .A1(\memory[7] [0]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [0]),
    .ZN(_092_)
  );
  NOR3_X1 _258_ (
    .A1(rd_ptr[0]),
    .A2(_000_),
    .A3(_001_),
    .ZN(_093_)
  );
  NOR3_X1 _259_ (
    .A1(rd_ptr[0]),
    .A2(rd_ptr[2]),
    .A3(_001_),
    .ZN(_094_)
  );
  AOI22_X1 _260_ (
    .A1(\memory[6] [0]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [0]),
    .ZN(_095_)
  );
  NOR3_X1 _261_ (
    .A1(_233_[0]),
    .A2(rd_ptr[1]),
    .A3(_000_),
    .ZN(_096_)
  );
  NOR3_X1 _262_ (
    .A1(_233_[0]),
    .A2(rd_ptr[2]),
    .A3(_001_),
    .ZN(_097_)
  );
  AOI22_X1 _263_ (
    .A1(\memory[5] [0]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [0]),
    .ZN(_098_)
  );
  NOR3_X1 _264_ (
    .A1(_233_[0]),
    .A2(rd_ptr[1]),
    .A3(rd_ptr[2]),
    .ZN(_099_)
  );
  NOR3_X1 _265_ (
    .A1(rd_ptr[0]),
    .A2(rd_ptr[1]),
    .A3(_000_),
    .ZN(_100_)
  );
  AOI22_X1 _266_ (
    .A1(\memory[1] [0]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [0]),
    .ZN(_101_)
  );
  NAND4_X1 _267_ (
    .A1(_092_),
    .A2(_095_),
    .A3(_098_),
    .A4(_101_),
    .ZN(_102_)
  );
  MUX2_X1 _268_ (
    .A(data_out[0]),
    .B(_102_),
    .S(rd_en),
    .Z(_019_)
  );
  AOI22_X1 _269_ (
    .A1(\memory[7] [1]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [1]),
    .ZN(_103_)
  );
  AOI22_X1 _270_ (
    .A1(\memory[6] [1]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [1]),
    .ZN(_104_)
  );
  AOI22_X1 _271_ (
    .A1(\memory[5] [1]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [1]),
    .ZN(_105_)
  );
  AOI22_X1 _272_ (
    .A1(\memory[1] [1]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [1]),
    .ZN(_106_)
  );
  NAND4_X1 _273_ (
    .A1(_103_),
    .A2(_104_),
    .A3(_105_),
    .A4(_106_),
    .ZN(_107_)
  );
  MUX2_X1 _274_ (
    .A(data_out[1]),
    .B(_107_),
    .S(rd_en),
    .Z(_020_)
  );
  AOI22_X1 _275_ (
    .A1(\memory[7] [2]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [2]),
    .ZN(_108_)
  );
  AOI22_X1 _276_ (
    .A1(\memory[6] [2]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [2]),
    .ZN(_109_)
  );
  AOI22_X1 _277_ (
    .A1(\memory[5] [2]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [2]),
    .ZN(_110_)
  );
  AOI22_X1 _278_ (
    .A1(\memory[1] [2]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [2]),
    .ZN(_111_)
  );
  NAND4_X1 _279_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_110_),
    .A4(_111_),
    .ZN(_112_)
  );
  MUX2_X1 _280_ (
    .A(data_out[2]),
    .B(_112_),
    .S(rd_en),
    .Z(_021_)
  );
  AOI22_X1 _281_ (
    .A1(\memory[7] [3]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [3]),
    .ZN(_113_)
  );
  AOI22_X1 _282_ (
    .A1(\memory[6] [3]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [3]),
    .ZN(_114_)
  );
  AOI22_X1 _283_ (
    .A1(\memory[5] [3]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [3]),
    .ZN(_115_)
  );
  AOI22_X1 _284_ (
    .A1(\memory[1] [3]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [3]),
    .ZN(_116_)
  );
  NAND4_X1 _285_ (
    .A1(_113_),
    .A2(_114_),
    .A3(_115_),
    .A4(_116_),
    .ZN(_117_)
  );
  MUX2_X1 _286_ (
    .A(data_out[3]),
    .B(_117_),
    .S(rd_en),
    .Z(_022_)
  );
  AOI22_X1 _287_ (
    .A1(\memory[7] [4]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [4]),
    .ZN(_118_)
  );
  AOI22_X1 _288_ (
    .A1(\memory[6] [4]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [4]),
    .ZN(_119_)
  );
  AOI22_X1 _289_ (
    .A1(\memory[5] [4]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [4]),
    .ZN(_120_)
  );
  AOI22_X1 _290_ (
    .A1(\memory[1] [4]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [4]),
    .ZN(_121_)
  );
  NAND4_X1 _291_ (
    .A1(_118_),
    .A2(_119_),
    .A3(_120_),
    .A4(_121_),
    .ZN(_122_)
  );
  MUX2_X1 _292_ (
    .A(data_out[4]),
    .B(_122_),
    .S(rd_en),
    .Z(_023_)
  );
  AOI22_X1 _293_ (
    .A1(\memory[7] [5]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [5]),
    .ZN(_123_)
  );
  AOI22_X1 _294_ (
    .A1(\memory[6] [5]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [5]),
    .ZN(_124_)
  );
  AOI22_X1 _295_ (
    .A1(\memory[5] [5]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [5]),
    .ZN(_125_)
  );
  AOI22_X1 _296_ (
    .A1(\memory[1] [5]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [5]),
    .ZN(_126_)
  );
  NAND4_X1 _297_ (
    .A1(_123_),
    .A2(_124_),
    .A3(_125_),
    .A4(_126_),
    .ZN(_127_)
  );
  MUX2_X1 _298_ (
    .A(data_out[5]),
    .B(_127_),
    .S(rd_en),
    .Z(_024_)
  );
  AOI22_X1 _299_ (
    .A1(\memory[7] [6]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [6]),
    .ZN(_128_)
  );
  AOI22_X1 _300_ (
    .A1(\memory[6] [6]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [6]),
    .ZN(_129_)
  );
  AOI22_X1 _301_ (
    .A1(\memory[5] [6]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [6]),
    .ZN(_130_)
  );
  AOI22_X1 _302_ (
    .A1(\memory[1] [6]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [6]),
    .ZN(_131_)
  );
  NAND4_X1 _303_ (
    .A1(_128_),
    .A2(_129_),
    .A3(_130_),
    .A4(_131_),
    .ZN(_132_)
  );
  MUX2_X1 _304_ (
    .A(data_out[6]),
    .B(_132_),
    .S(rd_en),
    .Z(_025_)
  );
  AOI22_X1 _305_ (
    .A1(\memory[7] [7]),
    .A2(_090_),
    .B1(_091_),
    .B2(\memory[0] [7]),
    .ZN(_133_)
  );
  AOI22_X1 _306_ (
    .A1(\memory[6] [7]),
    .A2(_093_),
    .B1(_094_),
    .B2(\memory[2] [7]),
    .ZN(_134_)
  );
  AOI22_X1 _307_ (
    .A1(\memory[5] [7]),
    .A2(_096_),
    .B1(_097_),
    .B2(\memory[3] [7]),
    .ZN(_135_)
  );
  AOI22_X1 _308_ (
    .A1(\memory[1] [7]),
    .A2(_099_),
    .B1(_100_),
    .B2(\memory[4] [7]),
    .ZN(_136_)
  );
  NAND4_X1 _309_ (
    .A1(_133_),
    .A2(_134_),
    .A3(_135_),
    .A4(_136_),
    .ZN(_137_)
  );
  MUX2_X1 _310_ (
    .A(data_out[7]),
    .B(_137_),
    .S(rd_en),
    .Z(_026_)
  );
  NOR2_X1 _311_ (
    .A1(_232_[0]),
    .A2(wr_ptr[1]),
    .ZN(_138_)
  );
  NAND2_X1 _312_ (
    .A1(_086_),
    .A2(_138_),
    .ZN(_139_)
  );
  MUX2_X1 _313_ (
    .A(data_in[0]),
    .B(\memory[5] [0]),
    .S(_139_),
    .Z(_027_)
  );
  MUX2_X1 _314_ (
    .A(data_in[1]),
    .B(\memory[5] [1]),
    .S(_139_),
    .Z(_028_)
  );
  MUX2_X1 _315_ (
    .A(data_in[2]),
    .B(\memory[5] [2]),
    .S(_139_),
    .Z(_029_)
  );
  MUX2_X1 _316_ (
    .A(data_in[3]),
    .B(\memory[5] [3]),
    .S(_139_),
    .Z(_030_)
  );
  MUX2_X1 _317_ (
    .A(data_in[4]),
    .B(\memory[5] [4]),
    .S(_139_),
    .Z(_031_)
  );
  MUX2_X1 _318_ (
    .A(data_in[5]),
    .B(\memory[5] [5]),
    .S(_139_),
    .Z(_032_)
  );
  MUX2_X1 _319_ (
    .A(data_in[6]),
    .B(\memory[5] [6]),
    .S(_139_),
    .Z(_033_)
  );
  MUX2_X1 _320_ (
    .A(data_in[7]),
    .B(\memory[5] [7]),
    .S(_139_),
    .Z(_034_)
  );
  MUX2_X1 _321_ (
    .A(wr_ptr[0]),
    .B(_232_[0]),
    .S(wr_en),
    .Z(_035_)
  );
  NOR2_X1 _322_ (
    .A1(wr_ptr[0]),
    .A2(wr_ptr[1]),
    .ZN(_140_)
  );
  XOR2_X1 _323_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Z(_141_)
  );
  MUX2_X1 _324_ (
    .A(wr_ptr[1]),
    .B(_141_),
    .S(wr_en),
    .Z(_036_)
  );
  NAND3_X1 _325_ (
    .A1(wr_ptr[0]),
    .A2(wr_en),
    .A3(wr_ptr[1]),
    .ZN(_142_)
  );
  NAND4_X1 _326_ (
    .A1(wr_ptr[0]),
    .A2(wr_en),
    .A3(wr_ptr[1]),
    .A4(wr_ptr[2]),
    .ZN(_143_)
  );
  XNOR2_X1 _327_ (
    .A(wr_ptr[2]),
    .B(_142_),
    .ZN(_037_)
  );
  XNOR2_X1 _328_ (
    .A(wr_ptr[3]),
    .B(_143_),
    .ZN(_038_)
  );
  MUX2_X1 _329_ (
    .A(rd_ptr[0]),
    .B(_233_[0]),
    .S(rd_en),
    .Z(_039_)
  );
  XOR2_X1 _330_ (
    .A(rd_ptr[0]),
    .B(rd_ptr[1]),
    .Z(_144_)
  );
  MUX2_X1 _331_ (
    .A(rd_ptr[1]),
    .B(_144_),
    .S(rd_en),
    .Z(_040_)
  );
  NAND3_X1 _332_ (
    .A1(rd_en),
    .A2(rd_ptr[0]),
    .A3(rd_ptr[1]),
    .ZN(_145_)
  );
  NAND4_X1 _333_ (
    .A1(rd_en),
    .A2(rd_ptr[0]),
    .A3(rd_ptr[1]),
    .A4(rd_ptr[2]),
    .ZN(_146_)
  );
  XNOR2_X1 _334_ (
    .A(rd_ptr[2]),
    .B(_145_),
    .ZN(_041_)
  );
  XNOR2_X1 _335_ (
    .A(rd_ptr[3]),
    .B(_146_),
    .ZN(_042_)
  );
  NOR2_X1 _336_ (
    .A1(_084_),
    .A2(wr_ptr[2]),
    .ZN(_147_)
  );
  NAND2_X1 _337_ (
    .A1(_140_),
    .A2(_147_),
    .ZN(_148_)
  );
  MUX2_X1 _338_ (
    .A(data_in[0]),
    .B(\memory[0] [0]),
    .S(_148_),
    .Z(_043_)
  );
  MUX2_X1 _339_ (
    .A(data_in[1]),
    .B(\memory[0] [1]),
    .S(_148_),
    .Z(_044_)
  );
  MUX2_X1 _340_ (
    .A(data_in[2]),
    .B(\memory[0] [2]),
    .S(_148_),
    .Z(_045_)
  );
  MUX2_X1 _341_ (
    .A(data_in[3]),
    .B(\memory[0] [3]),
    .S(_148_),
    .Z(_046_)
  );
  MUX2_X1 _342_ (
    .A(data_in[4]),
    .B(\memory[0] [4]),
    .S(_148_),
    .Z(_047_)
  );
  MUX2_X1 _343_ (
    .A(data_in[5]),
    .B(\memory[0] [5]),
    .S(_148_),
    .Z(_048_)
  );
  MUX2_X1 _344_ (
    .A(data_in[6]),
    .B(\memory[0] [6]),
    .S(_148_),
    .Z(_049_)
  );
  MUX2_X1 _345_ (
    .A(data_in[7]),
    .B(\memory[0] [7]),
    .S(_148_),
    .Z(_050_)
  );
  NAND2_X1 _346_ (
    .A1(_138_),
    .A2(_147_),
    .ZN(_149_)
  );
  MUX2_X1 _347_ (
    .A(data_in[0]),
    .B(\memory[1] [0]),
    .S(_149_),
    .Z(_051_)
  );
  MUX2_X1 _348_ (
    .A(data_in[1]),
    .B(\memory[1] [1]),
    .S(_149_),
    .Z(_052_)
  );
  MUX2_X1 _349_ (
    .A(data_in[2]),
    .B(\memory[1] [2]),
    .S(_149_),
    .Z(_053_)
  );
  MUX2_X1 _350_ (
    .A(data_in[3]),
    .B(\memory[1] [3]),
    .S(_149_),
    .Z(_054_)
  );
  MUX2_X1 _351_ (
    .A(data_in[4]),
    .B(\memory[1] [4]),
    .S(_149_),
    .Z(_055_)
  );
  MUX2_X1 _352_ (
    .A(data_in[5]),
    .B(\memory[1] [5]),
    .S(_149_),
    .Z(_056_)
  );
  MUX2_X1 _353_ (
    .A(data_in[6]),
    .B(\memory[1] [6]),
    .S(_149_),
    .Z(_057_)
  );
  MUX2_X1 _354_ (
    .A(data_in[7]),
    .B(\memory[1] [7]),
    .S(_149_),
    .Z(_058_)
  );
  NAND2_X1 _355_ (
    .A1(_085_),
    .A2(_147_),
    .ZN(_150_)
  );
  MUX2_X1 _356_ (
    .A(data_in[0]),
    .B(\memory[2] [0]),
    .S(_150_),
    .Z(_059_)
  );
  MUX2_X1 _357_ (
    .A(data_in[1]),
    .B(\memory[2] [1]),
    .S(_150_),
    .Z(_060_)
  );
  MUX2_X1 _358_ (
    .A(data_in[2]),
    .B(\memory[2] [2]),
    .S(_150_),
    .Z(_061_)
  );
  MUX2_X1 _359_ (
    .A(data_in[3]),
    .B(\memory[2] [3]),
    .S(_150_),
    .Z(_062_)
  );
  MUX2_X1 _360_ (
    .A(data_in[4]),
    .B(\memory[2] [4]),
    .S(_150_),
    .Z(_063_)
  );
  MUX2_X1 _361_ (
    .A(data_in[5]),
    .B(\memory[2] [5]),
    .S(_150_),
    .Z(_064_)
  );
  MUX2_X1 _362_ (
    .A(data_in[6]),
    .B(\memory[2] [6]),
    .S(_150_),
    .Z(_065_)
  );
  MUX2_X1 _363_ (
    .A(data_in[7]),
    .B(\memory[2] [7]),
    .S(_150_),
    .Z(_066_)
  );
  NAND2_X1 _364_ (
    .A1(_088_),
    .A2(_147_),
    .ZN(_151_)
  );
  MUX2_X1 _365_ (
    .A(data_in[0]),
    .B(\memory[3] [0]),
    .S(_151_),
    .Z(_067_)
  );
  MUX2_X1 _366_ (
    .A(data_in[1]),
    .B(\memory[3] [1]),
    .S(_151_),
    .Z(_068_)
  );
  MUX2_X1 _367_ (
    .A(data_in[2]),
    .B(\memory[3] [2]),
    .S(_151_),
    .Z(_069_)
  );
  MUX2_X1 _368_ (
    .A(data_in[3]),
    .B(\memory[3] [3]),
    .S(_151_),
    .Z(_070_)
  );
  MUX2_X1 _369_ (
    .A(data_in[4]),
    .B(\memory[3] [4]),
    .S(_151_),
    .Z(_071_)
  );
  MUX2_X1 _370_ (
    .A(data_in[5]),
    .B(\memory[3] [5]),
    .S(_151_),
    .Z(_072_)
  );
  MUX2_X1 _371_ (
    .A(data_in[6]),
    .B(\memory[3] [6]),
    .S(_151_),
    .Z(_073_)
  );
  MUX2_X1 _372_ (
    .A(data_in[7]),
    .B(\memory[3] [7]),
    .S(_151_),
    .Z(_074_)
  );
  NAND2_X1 _373_ (
    .A1(_086_),
    .A2(_140_),
    .ZN(_152_)
  );
  MUX2_X1 _374_ (
    .A(data_in[0]),
    .B(\memory[4] [0]),
    .S(_152_),
    .Z(_075_)
  );
  MUX2_X1 _375_ (
    .A(data_in[1]),
    .B(\memory[4] [1]),
    .S(_152_),
    .Z(_076_)
  );
  MUX2_X1 _376_ (
    .A(data_in[2]),
    .B(\memory[4] [2]),
    .S(_152_),
    .Z(_077_)
  );
  MUX2_X1 _377_ (
    .A(data_in[3]),
    .B(\memory[4] [3]),
    .S(_152_),
    .Z(_078_)
  );
  MUX2_X1 _378_ (
    .A(data_in[4]),
    .B(\memory[4] [4]),
    .S(_152_),
    .Z(_079_)
  );
  MUX2_X1 _379_ (
    .A(data_in[5]),
    .B(\memory[4] [5]),
    .S(_152_),
    .Z(_080_)
  );
  MUX2_X1 _380_ (
    .A(data_in[6]),
    .B(\memory[4] [6]),
    .S(_152_),
    .Z(_081_)
  );
  MUX2_X1 _381_ (
    .A(data_in[7]),
    .B(\memory[4] [7]),
    .S(_152_),
    .Z(_082_)
  );
  MUX2_X1 _382_ (
    .A(data_in[0]),
    .B(\memory[6] [0]),
    .S(_087_),
    .Z(_083_)
  );
  XNOR2_X1 _383_ (
    .A(wr_ptr[1]),
    .B(rd_ptr[1]),
    .ZN(_153_)
  );
  XNOR2_X1 _384_ (
    .A(wr_ptr[0]),
    .B(rd_ptr[0]),
    .ZN(_154_)
  );
  XNOR2_X1 _385_ (
    .A(wr_ptr[2]),
    .B(rd_ptr[2]),
    .ZN(_155_)
  );
  NAND3_X1 _386_ (
    .A1(_153_),
    .A2(_154_),
    .A3(_155_),
    .ZN(_156_)
  );
  XOR2_X1 _387_ (
    .A(wr_ptr[3]),
    .B(rd_ptr[3]),
    .Z(_157_)
  );
  NOR2_X1 _388_ (
    .A1(_156_),
    .A2(_157_),
    .ZN(empty)
  );
  AND4_X1 _389_ (
    .A1(_153_),
    .A2(_154_),
    .A3(_155_),
    .A4(_157_),
    .ZN(full)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _390_ (
    .CK(clk),
    .D(_027_),
    .Q(\memory[5] [0]),
    .QN(_231_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _391_ (
    .CK(clk),
    .D(_028_),
    .Q(\memory[5] [1]),
    .QN(_230_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _392_ (
    .CK(clk),
    .D(_029_),
    .Q(\memory[5] [2]),
    .QN(_229_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _393_ (
    .CK(clk),
    .D(_030_),
    .Q(\memory[5] [3]),
    .QN(_228_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _394_ (
    .CK(clk),
    .D(_031_),
    .Q(\memory[5] [4]),
    .QN(_227_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _395_ (
    .CK(clk),
    .D(_032_),
    .Q(\memory[5] [5]),
    .QN(_226_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _396_ (
    .CK(clk),
    .D(_033_),
    .Q(\memory[5] [6]),
    .QN(_225_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _397_ (
    .CK(clk),
    .D(_034_),
    .Q(\memory[5] [7]),
    .QN(_224_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _398_ (
    .CK(clk),
    .D(_035_),
    .Q(wr_ptr[0]),
    .QN(_232_[0]),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _399_ (
    .CK(clk),
    .D(_036_),
    .Q(wr_ptr[1]),
    .QN(_003_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _400_ (
    .CK(clk),
    .D(_037_),
    .Q(wr_ptr[2]),
    .QN(_002_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _401_ (
    .CK(clk),
    .D(_038_),
    .Q(wr_ptr[3]),
    .QN(_223_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _402_ (
    .CK(clk),
    .D(_039_),
    .Q(rd_ptr[0]),
    .QN(_233_[0]),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _403_ (
    .CK(clk),
    .D(_040_),
    .Q(rd_ptr[1]),
    .QN(_001_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _404_ (
    .CK(clk),
    .D(_041_),
    .Q(rd_ptr[2]),
    .QN(_000_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _405_ (
    .CK(clk),
    .D(_042_),
    .Q(rd_ptr[3]),
    .QN(_222_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _406_ (
    .CK(clk),
    .D(_043_),
    .Q(\memory[0] [0]),
    .QN(_221_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _407_ (
    .CK(clk),
    .D(_044_),
    .Q(\memory[0] [1]),
    .QN(_220_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _408_ (
    .CK(clk),
    .D(_045_),
    .Q(\memory[0] [2]),
    .QN(_219_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _409_ (
    .CK(clk),
    .D(_046_),
    .Q(\memory[0] [3]),
    .QN(_218_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _410_ (
    .CK(clk),
    .D(_047_),
    .Q(\memory[0] [4]),
    .QN(_217_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _411_ (
    .CK(clk),
    .D(_048_),
    .Q(\memory[0] [5]),
    .QN(_216_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _412_ (
    .CK(clk),
    .D(_049_),
    .Q(\memory[0] [6]),
    .QN(_215_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _413_ (
    .CK(clk),
    .D(_050_),
    .Q(\memory[0] [7]),
    .QN(_214_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _414_ (
    .CK(clk),
    .D(_051_),
    .Q(\memory[1] [0]),
    .QN(_213_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _415_ (
    .CK(clk),
    .D(_052_),
    .Q(\memory[1] [1]),
    .QN(_212_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _416_ (
    .CK(clk),
    .D(_053_),
    .Q(\memory[1] [2]),
    .QN(_211_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _417_ (
    .CK(clk),
    .D(_054_),
    .Q(\memory[1] [3]),
    .QN(_210_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _418_ (
    .CK(clk),
    .D(_055_),
    .Q(\memory[1] [4]),
    .QN(_209_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _419_ (
    .CK(clk),
    .D(_056_),
    .Q(\memory[1] [5]),
    .QN(_208_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _420_ (
    .CK(clk),
    .D(_057_),
    .Q(\memory[1] [6]),
    .QN(_207_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _421_ (
    .CK(clk),
    .D(_058_),
    .Q(\memory[1] [7]),
    .QN(_206_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _422_ (
    .CK(clk),
    .D(_059_),
    .Q(\memory[2] [0]),
    .QN(_205_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _423_ (
    .CK(clk),
    .D(_060_),
    .Q(\memory[2] [1]),
    .QN(_204_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _424_ (
    .CK(clk),
    .D(_061_),
    .Q(\memory[2] [2]),
    .QN(_203_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _425_ (
    .CK(clk),
    .D(_062_),
    .Q(\memory[2] [3]),
    .QN(_202_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _426_ (
    .CK(clk),
    .D(_063_),
    .Q(\memory[2] [4]),
    .QN(_201_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _427_ (
    .CK(clk),
    .D(_064_),
    .Q(\memory[2] [5]),
    .QN(_200_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _428_ (
    .CK(clk),
    .D(_065_),
    .Q(\memory[2] [6]),
    .QN(_199_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _429_ (
    .CK(clk),
    .D(_066_),
    .Q(\memory[2] [7]),
    .QN(_198_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _430_ (
    .CK(clk),
    .D(_067_),
    .Q(\memory[3] [0]),
    .QN(_197_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _431_ (
    .CK(clk),
    .D(_068_),
    .Q(\memory[3] [1]),
    .QN(_196_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _432_ (
    .CK(clk),
    .D(_069_),
    .Q(\memory[3] [2]),
    .QN(_195_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _433_ (
    .CK(clk),
    .D(_070_),
    .Q(\memory[3] [3]),
    .QN(_194_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _434_ (
    .CK(clk),
    .D(_071_),
    .Q(\memory[3] [4]),
    .QN(_193_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _435_ (
    .CK(clk),
    .D(_072_),
    .Q(\memory[3] [5]),
    .QN(_192_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _436_ (
    .CK(clk),
    .D(_073_),
    .Q(\memory[3] [6]),
    .QN(_191_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _437_ (
    .CK(clk),
    .D(_074_),
    .Q(\memory[3] [7]),
    .QN(_190_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _438_ (
    .CK(clk),
    .D(_075_),
    .Q(\memory[4] [0]),
    .QN(_189_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _439_ (
    .CK(clk),
    .D(_076_),
    .Q(\memory[4] [1]),
    .QN(_188_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _440_ (
    .CK(clk),
    .D(_077_),
    .Q(\memory[4] [2]),
    .QN(_187_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _441_ (
    .CK(clk),
    .D(_078_),
    .Q(\memory[4] [3]),
    .QN(_186_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _442_ (
    .CK(clk),
    .D(_079_),
    .Q(\memory[4] [4]),
    .QN(_185_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _443_ (
    .CK(clk),
    .D(_080_),
    .Q(\memory[4] [5]),
    .QN(_184_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _444_ (
    .CK(clk),
    .D(_081_),
    .Q(\memory[4] [6]),
    .QN(_183_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _445_ (
    .CK(clk),
    .D(_082_),
    .Q(\memory[4] [7]),
    .QN(_182_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _446_ (
    .CK(clk),
    .D(_083_),
    .Q(\memory[6] [0]),
    .QN(_181_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _447_ (
    .CK(clk),
    .D(_004_),
    .Q(\memory[6] [1]),
    .QN(_180_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _448_ (
    .CK(clk),
    .D(_005_),
    .Q(\memory[6] [2]),
    .QN(_179_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _449_ (
    .CK(clk),
    .D(_006_),
    .Q(\memory[6] [3]),
    .QN(_178_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _450_ (
    .CK(clk),
    .D(_007_),
    .Q(\memory[6] [4]),
    .QN(_177_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _451_ (
    .CK(clk),
    .D(_008_),
    .Q(\memory[6] [5]),
    .QN(_176_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _452_ (
    .CK(clk),
    .D(_009_),
    .Q(\memory[6] [6]),
    .QN(_175_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _453_ (
    .CK(clk),
    .D(_010_),
    .Q(\memory[6] [7]),
    .QN(_174_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _454_ (
    .CK(clk),
    .D(_011_),
    .Q(\memory[7] [0]),
    .QN(_173_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _455_ (
    .CK(clk),
    .D(_012_),
    .Q(\memory[7] [1]),
    .QN(_172_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _456_ (
    .CK(clk),
    .D(_013_),
    .Q(\memory[7] [2]),
    .QN(_171_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _457_ (
    .CK(clk),
    .D(_014_),
    .Q(\memory[7] [3]),
    .QN(_170_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _458_ (
    .CK(clk),
    .D(_015_),
    .Q(\memory[7] [4]),
    .QN(_169_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _459_ (
    .CK(clk),
    .D(_016_),
    .Q(\memory[7] [5]),
    .QN(_168_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _460_ (
    .CK(clk),
    .D(_017_),
    .Q(\memory[7] [6]),
    .QN(_167_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _461_ (
    .CK(clk),
    .D(_018_),
    .Q(\memory[7] [7]),
    .QN(_166_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _462_ (
    .CK(clk),
    .D(_019_),
    .Q(data_out[0]),
    .QN(_165_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _463_ (
    .CK(clk),
    .D(_020_),
    .Q(data_out[1]),
    .QN(_164_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _464_ (
    .CK(clk),
    .D(_021_),
    .Q(data_out[2]),
    .QN(_163_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _465_ (
    .CK(clk),
    .D(_022_),
    .Q(data_out[3]),
    .QN(_162_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _466_ (
    .CK(clk),
    .D(_023_),
    .Q(data_out[4]),
    .QN(_161_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _467_ (
    .CK(clk),
    .D(_024_),
    .Q(data_out[5]),
    .QN(_160_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _468_ (
    .CK(clk),
    .D(_025_),
    .Q(data_out[6]),
    .QN(_159_),
    .RN(rst)
  );
  (* src = "synch_fifo.v:16.1-38.4" *)
  DFFR_X1 _469_ (
    .CK(clk),
    .D(_026_),
    .Q(data_out[7]),
    .QN(_158_),
    .RN(rst)
  );
  assign _232_[3:1] = wr_ptr[3:1];
  assign _233_[3:1] = rd_ptr[3:1];
  assign i = 32'd8;
endmodule
